### ISSUE TITLE
Most probably the changes related to serialisation/deserialisation is breaking for some cameras

### ISSUE THREAD

**Issue by momshaddinury** [faithoflifedev/easy_onvif_workspace#71]
Our sunba cameras used to work with onvif protocol. But after the recent update onvif is failing to connect.
Here is the error log:
```
[log] #0      OnvifUtil.xmlToMap (package:easy_onvif/src/util/util.dart:22:30)
#1      new Envelope.fromXmlString (package:easy_onvif/src/model/envelope.dart:26:35)
#2      Transport.sendRequest (package:easy_onvif/src/soap/transport.dart:92:21)
<asynchronous suspension>
#3      Transport.request (package:easy_onvif/src/soap/transport.dart:130:57)
<asynchronous suspension>
#4      DeviceManagement.getSystemDateAndTime (package:easy_onvif/src/device_management.dart:370:30)
<asynchronous suspension>
#5      Onvif.getTimeDelta (package:easy_onvif/src/onvif_base.dart:117:22)
```

**Comment by faithoflifedev** [comment]
Hi @momshaddinury,

I can't replicate this issue with the devices I have available to me.  Is it possible for you to provide the XML response from the device.  You can get it with the following commands:

```sh
#install the easy_onvif cli utility
dart pub global activate easy_onvif_cli

#provide connection and authentication for the device (ipaddress:port, username, passowrd)
onvif authorize

# make the GetSystemDateAndTime request to the device and write the response to the debug.txt file
onvif device-management get-system-date-and-time --log-level all > debug.txt
```

Once I can see the response I should be able to debug the isue.

**Comment by cdavis-venngo** [comment]
@momshaddinury is this still an issue?

**Comment by momshaddinury** [comment]
> @momshaddinury is this still an issue? 

Yes, it is. I was busy with a release so couldn't get back to this. I'll try to share the cli logs this week
